# Generated by Django 6.0 on 2026-01-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0041_v2_8__address_created_n_modified02'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entity_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code entité'),
        ),
        migrations.AddField(
            model_name='contact',
            name='entity_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Libellé entité'),
        ),
        migrations.AddField(
            model_name='contact',
            name='entity_type_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code type entité'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_entity_subject',
            field=models.BooleanField(default=False, verbose_name='Assujetti entité'),
        ),
    ]
