# Generated by Django 6.0 on 2026-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0042_contact_entity_code_contact_entity_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_in_mailing',
            field=models.BooleanField(default=False, verbose_name="Inclus dans l'e-mailing"),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_in_taxe',
            field=models.BooleanField(default=False, verbose_name='Inclus dans la taxe'),
        ),
    ]
