# Generated by Django 6.0 on 2026-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0043_contact_is_in_mailing_contact_is_in_taxe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_in_mailing',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=3, verbose_name="Inscrire à l'E-mailing ?"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_in_taxe',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], default='NON', max_length=3, verbose_name='Inscrire à la Taxe ?'),
        ),
    ]
