# Generated by Django 6.0 on 2026-02-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0044_alter_contact_is_in_mailing_alter_contact_is_in_taxe'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse (Ligne 1)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_data',
            field=models.TextField(blank=True, verbose_name='Données Consentement'),
        ),
        migrations.AddField(
            model_name='contact',
            name='coordonnees_raw',
            field=models.TextField(blank=True, verbose_name='Coordonnées (Raw)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='education_montant_taxe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Montant Taxe'),
        ),
        migrations.AddField(
            model_name='contact',
            name='education_nb_stagiaires',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de stagiaire'),
        ),
        migrations.AddField(
            model_name='contact',
            name='import_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Statut Import'),
        ),
    ]
