# Generated by Django 6.0 on 2026-07-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0045_contact_address_city_contact_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='education_montant_taxe',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_in_mailing',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_in_taxe',
        ),
    ]
